# Generated by Django 5.1.1 on 2024-09-11 01:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat', '0003_alter_thread_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
